{% set name = "pluggy" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pluggy-{{ version }}.tar.gz
  sha256: 4224373bacce55f955a878bf9cfa763c1e360858e330072059e10bad68531159

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 5

requirements:
  host:
    - python
    - setuptools-scm
    - pip
  run:
    - python
    - importlib-metadata >=0.12

test:
  imports:
    - pluggy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytest-dev/pluggy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Plugin registration and hook calling for Python
  doc_url: https://pluggy.readthedocs.io/en/latest/
  dev_url: https://github.com/pytest-dev/pluggy/

extra:
  recipe-maintainers:
    - johnnygenomics
    - nicoddemus
    - adriendelsalle
